saturation: 5
speed: 2
eatingProbabilities:
  "com.eugened.entity.object.organism.animal.predator.creatures.Boa": 0.8
  "com.eugened.entity.object.organism.animal.herbivore.creatures.Horse": 0.4
  "com.eugened.entity.object.organism.animal.herbivore.creatures.Deer": 0.8
  "com.eugened.entity.object.organism.animal.herbivore.creatures.Rabbit": 0.9
  "com.eugened.entity.object.organism.animal.herbivore.creatures.Mouse": 0.7
  "com.eugened.entity.object.organism.animal.herbivore.creatures.Goat": 0.6
  "com.eugened.entity.object.organism.animal.herbivore.creatures.Sheep": 0.5
  "com.eugened.entity.object.organism.animal.herbivore.creatures.Boar": 0.4
  "com.eugened.entity.object.organism.animal.herbivore.creatures.Buffalo": 0.2
  "com.eugened.entity.object.organism.animal.herbivore.creatures.Duck": 0.1
