saturation: 30
speed: 2
eatingProbabilities:
  "com.eugened.entity.object.organism.animal.herbivore.creatures.Rabbit": 0.7
  "com.eugened.entity.object.organism.animal.herbivore.creatures.Mouse": 0.9
  "com.eugened.entity.object.organism.animal.herbivore.creatures.Duck": 0.6
  "com.eugened.entity.object.organism.animal.herbivore.creatures.Caterpillar": 0.4
