saturation: 30
speed: 3
eatingProbabilities:
  "com.eugened.entity.object.organism.animal.herbivore.creatures.Horse": 0.1
  "com.eugened.entity.object.organism.animal.herbivore.creatures.Deer": 0.15
  "com.eugened.entity.object.organism.animal.herbivore.creatures.Rabbit": 0.6
  "com.eugened.entity.object.organism.animal.herbivore.creatures.Mouse": 0.8
  "com.eugened.entity.object.organism.animal.herbivore.creatures.Goat": 0.6
  "com.eugened.entity.object.organism.animal.herbivore.creatures.Sheep": 0.7
  "com.eugened.entity.object.organism.animal.herbivore.creatures.Boar": 0.15
  "com.eugened.entity.object.organism.animal.herbivore.creatures.Buffalo": 0.1
  "com.eugened.entity.object.organism.animal.herbivore.creatures.Duck": 0.4
